// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: instrosetta/interfaces/light/light_source.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Instrosetta.Interfaces.Light.LightSource.V1 {
  public static partial class LightSource
  {
    static readonly string __ServiceName = "instrosetta.interfaces.light.light_source.v1.LightSource";

    static readonly grpc::Marshaller<global::Instrosetta.Interfaces.Light.LightSource.V1.InitializeRequest> __Marshaller_instrosetta_interfaces_light_light_source_v1_InitializeRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Instrosetta.Interfaces.Light.LightSource.V1.InitializeRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Instrosetta.Interfaces.Light.LightSource.V1.InitializeResponse> __Marshaller_instrosetta_interfaces_light_light_source_v1_InitializeResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Instrosetta.Interfaces.Light.LightSource.V1.InitializeResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Instrosetta.Interfaces.Light.LightSource.V1.ShutdownRequest> __Marshaller_instrosetta_interfaces_light_light_source_v1_ShutdownRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Instrosetta.Interfaces.Light.LightSource.V1.ShutdownRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Instrosetta.Interfaces.Light.LightSource.V1.ShutdownResponse> __Marshaller_instrosetta_interfaces_light_light_source_v1_ShutdownResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Instrosetta.Interfaces.Light.LightSource.V1.ShutdownResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Instrosetta.Interfaces.Light.LightSource.V1.GetPowerRequest> __Marshaller_instrosetta_interfaces_light_light_source_v1_GetPowerRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Instrosetta.Interfaces.Light.LightSource.V1.GetPowerRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Instrosetta.Interfaces.Light.LightSource.V1.GetPowerResponse> __Marshaller_instrosetta_interfaces_light_light_source_v1_GetPowerResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Instrosetta.Interfaces.Light.LightSource.V1.GetPowerResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Instrosetta.Interfaces.Light.LightSource.V1.SetPowerRequest> __Marshaller_instrosetta_interfaces_light_light_source_v1_SetPowerRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Instrosetta.Interfaces.Light.LightSource.V1.SetPowerRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Instrosetta.Interfaces.Light.LightSource.V1.SetPowerResponse> __Marshaller_instrosetta_interfaces_light_light_source_v1_SetPowerResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Instrosetta.Interfaces.Light.LightSource.V1.SetPowerResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Instrosetta.Interfaces.Light.LightSource.V1.InitializeRequest, global::Instrosetta.Interfaces.Light.LightSource.V1.InitializeResponse> __Method_Initialize = new grpc::Method<global::Instrosetta.Interfaces.Light.LightSource.V1.InitializeRequest, global::Instrosetta.Interfaces.Light.LightSource.V1.InitializeResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Initialize",
        __Marshaller_instrosetta_interfaces_light_light_source_v1_InitializeRequest,
        __Marshaller_instrosetta_interfaces_light_light_source_v1_InitializeResponse);

    static readonly grpc::Method<global::Instrosetta.Interfaces.Light.LightSource.V1.ShutdownRequest, global::Instrosetta.Interfaces.Light.LightSource.V1.ShutdownResponse> __Method_Shutdown = new grpc::Method<global::Instrosetta.Interfaces.Light.LightSource.V1.ShutdownRequest, global::Instrosetta.Interfaces.Light.LightSource.V1.ShutdownResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Shutdown",
        __Marshaller_instrosetta_interfaces_light_light_source_v1_ShutdownRequest,
        __Marshaller_instrosetta_interfaces_light_light_source_v1_ShutdownResponse);

    static readonly grpc::Method<global::Instrosetta.Interfaces.Light.LightSource.V1.GetPowerRequest, global::Instrosetta.Interfaces.Light.LightSource.V1.GetPowerResponse> __Method_GetPower = new grpc::Method<global::Instrosetta.Interfaces.Light.LightSource.V1.GetPowerRequest, global::Instrosetta.Interfaces.Light.LightSource.V1.GetPowerResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetPower",
        __Marshaller_instrosetta_interfaces_light_light_source_v1_GetPowerRequest,
        __Marshaller_instrosetta_interfaces_light_light_source_v1_GetPowerResponse);

    static readonly grpc::Method<global::Instrosetta.Interfaces.Light.LightSource.V1.SetPowerRequest, global::Instrosetta.Interfaces.Light.LightSource.V1.SetPowerResponse> __Method_SetPower = new grpc::Method<global::Instrosetta.Interfaces.Light.LightSource.V1.SetPowerRequest, global::Instrosetta.Interfaces.Light.LightSource.V1.SetPowerResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetPower",
        __Marshaller_instrosetta_interfaces_light_light_source_v1_SetPowerRequest,
        __Marshaller_instrosetta_interfaces_light_light_source_v1_SetPowerResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Instrosetta.Interfaces.Light.LightSource.V1.LightSourceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of LightSource</summary>
    public abstract partial class LightSourceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Instrosetta.Interfaces.Light.LightSource.V1.InitializeResponse> Initialize(global::Instrosetta.Interfaces.Light.LightSource.V1.InitializeRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Instrosetta.Interfaces.Light.LightSource.V1.ShutdownResponse> Shutdown(global::Instrosetta.Interfaces.Light.LightSource.V1.ShutdownRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Instrosetta.Interfaces.Light.LightSource.V1.GetPowerResponse> GetPower(global::Instrosetta.Interfaces.Light.LightSource.V1.GetPowerRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Instrosetta.Interfaces.Light.LightSource.V1.SetPowerResponse> SetPower(global::Instrosetta.Interfaces.Light.LightSource.V1.SetPowerRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for LightSource</summary>
    public partial class LightSourceClient : grpc::ClientBase<LightSourceClient>
    {
      /// <summary>Creates a new client for LightSource</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public LightSourceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for LightSource that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public LightSourceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected LightSourceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected LightSourceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Instrosetta.Interfaces.Light.LightSource.V1.InitializeResponse Initialize(global::Instrosetta.Interfaces.Light.LightSource.V1.InitializeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Initialize(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Instrosetta.Interfaces.Light.LightSource.V1.InitializeResponse Initialize(global::Instrosetta.Interfaces.Light.LightSource.V1.InitializeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Initialize, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Instrosetta.Interfaces.Light.LightSource.V1.InitializeResponse> InitializeAsync(global::Instrosetta.Interfaces.Light.LightSource.V1.InitializeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InitializeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Instrosetta.Interfaces.Light.LightSource.V1.InitializeResponse> InitializeAsync(global::Instrosetta.Interfaces.Light.LightSource.V1.InitializeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Initialize, null, options, request);
      }
      public virtual global::Instrosetta.Interfaces.Light.LightSource.V1.ShutdownResponse Shutdown(global::Instrosetta.Interfaces.Light.LightSource.V1.ShutdownRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Shutdown(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Instrosetta.Interfaces.Light.LightSource.V1.ShutdownResponse Shutdown(global::Instrosetta.Interfaces.Light.LightSource.V1.ShutdownRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Shutdown, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Instrosetta.Interfaces.Light.LightSource.V1.ShutdownResponse> ShutdownAsync(global::Instrosetta.Interfaces.Light.LightSource.V1.ShutdownRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ShutdownAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Instrosetta.Interfaces.Light.LightSource.V1.ShutdownResponse> ShutdownAsync(global::Instrosetta.Interfaces.Light.LightSource.V1.ShutdownRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Shutdown, null, options, request);
      }
      public virtual global::Instrosetta.Interfaces.Light.LightSource.V1.GetPowerResponse GetPower(global::Instrosetta.Interfaces.Light.LightSource.V1.GetPowerRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetPower(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Instrosetta.Interfaces.Light.LightSource.V1.GetPowerResponse GetPower(global::Instrosetta.Interfaces.Light.LightSource.V1.GetPowerRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetPower, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Instrosetta.Interfaces.Light.LightSource.V1.GetPowerResponse> GetPowerAsync(global::Instrosetta.Interfaces.Light.LightSource.V1.GetPowerRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetPowerAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Instrosetta.Interfaces.Light.LightSource.V1.GetPowerResponse> GetPowerAsync(global::Instrosetta.Interfaces.Light.LightSource.V1.GetPowerRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetPower, null, options, request);
      }
      public virtual global::Instrosetta.Interfaces.Light.LightSource.V1.SetPowerResponse SetPower(global::Instrosetta.Interfaces.Light.LightSource.V1.SetPowerRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPower(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Instrosetta.Interfaces.Light.LightSource.V1.SetPowerResponse SetPower(global::Instrosetta.Interfaces.Light.LightSource.V1.SetPowerRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetPower, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Instrosetta.Interfaces.Light.LightSource.V1.SetPowerResponse> SetPowerAsync(global::Instrosetta.Interfaces.Light.LightSource.V1.SetPowerRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPowerAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Instrosetta.Interfaces.Light.LightSource.V1.SetPowerResponse> SetPowerAsync(global::Instrosetta.Interfaces.Light.LightSource.V1.SetPowerRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetPower, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override LightSourceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new LightSourceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(LightSourceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Initialize, serviceImpl.Initialize)
          .AddMethod(__Method_Shutdown, serviceImpl.Shutdown)
          .AddMethod(__Method_GetPower, serviceImpl.GetPower)
          .AddMethod(__Method_SetPower, serviceImpl.SetPower).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, LightSourceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Initialize, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Instrosetta.Interfaces.Light.LightSource.V1.InitializeRequest, global::Instrosetta.Interfaces.Light.LightSource.V1.InitializeResponse>(serviceImpl.Initialize));
      serviceBinder.AddMethod(__Method_Shutdown, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Instrosetta.Interfaces.Light.LightSource.V1.ShutdownRequest, global::Instrosetta.Interfaces.Light.LightSource.V1.ShutdownResponse>(serviceImpl.Shutdown));
      serviceBinder.AddMethod(__Method_GetPower, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Instrosetta.Interfaces.Light.LightSource.V1.GetPowerRequest, global::Instrosetta.Interfaces.Light.LightSource.V1.GetPowerResponse>(serviceImpl.GetPower));
      serviceBinder.AddMethod(__Method_SetPower, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Instrosetta.Interfaces.Light.LightSource.V1.SetPowerRequest, global::Instrosetta.Interfaces.Light.LightSource.V1.SetPowerResponse>(serviceImpl.SetPower));
    }

  }
}
#endregion
