// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: instrosetta/interfaces/light_analysis/monochromator.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Instrosetta.Interfaces.LightAnalysis.Monochromator {
  public static partial class Monochromator
  {
    static readonly string __ServiceName = "instrosetta.interfaces.light_analysis.monochromator.Monochromator";

    static readonly grpc::Marshaller<global::ConnectRequest> __Marshaller_ConnectRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ConnectRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::ConnectResponse> __Marshaller_ConnectResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ConnectResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::DisconnectRequest> __Marshaller_DisconnectRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DisconnectRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::DisconnectResponse> __Marshaller_DisconnectResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DisconnectResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetWavelengthRangeRequest> __Marshaller_instrosetta_interfaces_light_analysis_monochromator_GetWavelengthRangeRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetWavelengthRangeRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetWavelengthRangeResponse> __Marshaller_instrosetta_interfaces_light_analysis_monochromator_GetWavelengthRangeResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetWavelengthRangeResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetWavelengthRequest> __Marshaller_instrosetta_interfaces_light_analysis_monochromator_GetWavelengthRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetWavelengthRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetWavelengthResponse> __Marshaller_instrosetta_interfaces_light_analysis_monochromator_GetWavelengthResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetWavelengthResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetWavelengthRequest> __Marshaller_instrosetta_interfaces_light_analysis_monochromator_SetWavelengthRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetWavelengthRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetWavelengthResponse> __Marshaller_instrosetta_interfaces_light_analysis_monochromator_SetWavelengthResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetWavelengthResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetGratingOptionsRequest> __Marshaller_instrosetta_interfaces_light_analysis_monochromator_GetGratingOptionsRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetGratingOptionsRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetGratingOptionsResponse> __Marshaller_instrosetta_interfaces_light_analysis_monochromator_GetGratingOptionsResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetGratingOptionsResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetGratingRequest> __Marshaller_instrosetta_interfaces_light_analysis_monochromator_GetGratingRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetGratingRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetGratingResponse> __Marshaller_instrosetta_interfaces_light_analysis_monochromator_GetGratingResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetGratingResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetGratingRequest> __Marshaller_instrosetta_interfaces_light_analysis_monochromator_SetGratingRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetGratingRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetGratingResponse> __Marshaller_instrosetta_interfaces_light_analysis_monochromator_SetGratingResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetGratingResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetSlitWidthRangeRequest> __Marshaller_instrosetta_interfaces_light_analysis_monochromator_GetSlitWidthRangeRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetSlitWidthRangeRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetSlitWidthRangeResponse> __Marshaller_instrosetta_interfaces_light_analysis_monochromator_GetSlitWidthRangeResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetSlitWidthRangeResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetSlitWidthRequest> __Marshaller_instrosetta_interfaces_light_analysis_monochromator_GetSlitWidthRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetSlitWidthRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetSlitWidthResponse> __Marshaller_instrosetta_interfaces_light_analysis_monochromator_GetSlitWidthResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetSlitWidthResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetSlitWidthRequest> __Marshaller_instrosetta_interfaces_light_analysis_monochromator_SetSlitWidthRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetSlitWidthRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetSlitWidthResponse> __Marshaller_instrosetta_interfaces_light_analysis_monochromator_SetSlitWidthResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetSlitWidthResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::ConnectRequest, global::ConnectResponse> __Method_Connect = new grpc::Method<global::ConnectRequest, global::ConnectResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Connect",
        __Marshaller_ConnectRequest,
        __Marshaller_ConnectResponse);

    static readonly grpc::Method<global::DisconnectRequest, global::DisconnectResponse> __Method_Disconnect = new grpc::Method<global::DisconnectRequest, global::DisconnectResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Disconnect",
        __Marshaller_DisconnectRequest,
        __Marshaller_DisconnectResponse);

    static readonly grpc::Method<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetWavelengthRangeRequest, global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetWavelengthRangeResponse> __Method_GetWavelengthRange = new grpc::Method<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetWavelengthRangeRequest, global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetWavelengthRangeResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetWavelengthRange",
        __Marshaller_instrosetta_interfaces_light_analysis_monochromator_GetWavelengthRangeRequest,
        __Marshaller_instrosetta_interfaces_light_analysis_monochromator_GetWavelengthRangeResponse);

    static readonly grpc::Method<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetWavelengthRequest, global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetWavelengthResponse> __Method_GetWavelength = new grpc::Method<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetWavelengthRequest, global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetWavelengthResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetWavelength",
        __Marshaller_instrosetta_interfaces_light_analysis_monochromator_GetWavelengthRequest,
        __Marshaller_instrosetta_interfaces_light_analysis_monochromator_GetWavelengthResponse);

    static readonly grpc::Method<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetWavelengthRequest, global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetWavelengthResponse> __Method_SetWavelength = new grpc::Method<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetWavelengthRequest, global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetWavelengthResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetWavelength",
        __Marshaller_instrosetta_interfaces_light_analysis_monochromator_SetWavelengthRequest,
        __Marshaller_instrosetta_interfaces_light_analysis_monochromator_SetWavelengthResponse);

    static readonly grpc::Method<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetGratingOptionsRequest, global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetGratingOptionsResponse> __Method_GetGratingOptions = new grpc::Method<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetGratingOptionsRequest, global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetGratingOptionsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetGratingOptions",
        __Marshaller_instrosetta_interfaces_light_analysis_monochromator_GetGratingOptionsRequest,
        __Marshaller_instrosetta_interfaces_light_analysis_monochromator_GetGratingOptionsResponse);

    static readonly grpc::Method<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetGratingRequest, global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetGratingResponse> __Method_GetGrating = new grpc::Method<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetGratingRequest, global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetGratingResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetGrating",
        __Marshaller_instrosetta_interfaces_light_analysis_monochromator_GetGratingRequest,
        __Marshaller_instrosetta_interfaces_light_analysis_monochromator_GetGratingResponse);

    static readonly grpc::Method<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetGratingRequest, global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetGratingResponse> __Method_SetGrating = new grpc::Method<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetGratingRequest, global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetGratingResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetGrating",
        __Marshaller_instrosetta_interfaces_light_analysis_monochromator_SetGratingRequest,
        __Marshaller_instrosetta_interfaces_light_analysis_monochromator_SetGratingResponse);

    static readonly grpc::Method<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetSlitWidthRangeRequest, global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetSlitWidthRangeResponse> __Method_GetSlitWidthRange = new grpc::Method<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetSlitWidthRangeRequest, global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetSlitWidthRangeResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetSlitWidthRange",
        __Marshaller_instrosetta_interfaces_light_analysis_monochromator_GetSlitWidthRangeRequest,
        __Marshaller_instrosetta_interfaces_light_analysis_monochromator_GetSlitWidthRangeResponse);

    static readonly grpc::Method<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetSlitWidthRequest, global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetSlitWidthResponse> __Method_GetSlitWidth = new grpc::Method<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetSlitWidthRequest, global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetSlitWidthResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetSlitWidth",
        __Marshaller_instrosetta_interfaces_light_analysis_monochromator_GetSlitWidthRequest,
        __Marshaller_instrosetta_interfaces_light_analysis_monochromator_GetSlitWidthResponse);

    static readonly grpc::Method<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetSlitWidthRequest, global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetSlitWidthResponse> __Method_SetSlitWidth = new grpc::Method<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetSlitWidthRequest, global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetSlitWidthResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetSlitWidth",
        __Marshaller_instrosetta_interfaces_light_analysis_monochromator_SetSlitWidthRequest,
        __Marshaller_instrosetta_interfaces_light_analysis_monochromator_SetSlitWidthResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Instrosetta.Interfaces.LightAnalysis.Monochromator.MonochromatorReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Monochromator</summary>
    public abstract partial class MonochromatorBase
    {
      public virtual global::System.Threading.Tasks.Task<global::ConnectResponse> Connect(global::ConnectRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::DisconnectResponse> Disconnect(global::DisconnectRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetWavelengthRangeResponse> GetWavelengthRange(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetWavelengthRangeRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetWavelengthResponse> GetWavelength(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetWavelengthRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetWavelengthResponse> SetWavelength(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetWavelengthRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetGratingOptionsResponse> GetGratingOptions(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetGratingOptionsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetGratingResponse> GetGrating(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetGratingRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetGratingResponse> SetGrating(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetGratingRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetSlitWidthRangeResponse> GetSlitWidthRange(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetSlitWidthRangeRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetSlitWidthResponse> GetSlitWidth(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetSlitWidthRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetSlitWidthResponse> SetSlitWidth(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetSlitWidthRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Monochromator</summary>
    public partial class MonochromatorClient : grpc::ClientBase<MonochromatorClient>
    {
      /// <summary>Creates a new client for Monochromator</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public MonochromatorClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Monochromator that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public MonochromatorClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected MonochromatorClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected MonochromatorClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::ConnectResponse Connect(global::ConnectRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Connect(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::ConnectResponse Connect(global::ConnectRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Connect, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::ConnectResponse> ConnectAsync(global::ConnectRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ConnectAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::ConnectResponse> ConnectAsync(global::ConnectRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Connect, null, options, request);
      }
      public virtual global::DisconnectResponse Disconnect(global::DisconnectRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Disconnect(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::DisconnectResponse Disconnect(global::DisconnectRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Disconnect, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::DisconnectResponse> DisconnectAsync(global::DisconnectRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DisconnectAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::DisconnectResponse> DisconnectAsync(global::DisconnectRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Disconnect, null, options, request);
      }
      public virtual global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetWavelengthRangeResponse GetWavelengthRange(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetWavelengthRangeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetWavelengthRange(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetWavelengthRangeResponse GetWavelengthRange(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetWavelengthRangeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetWavelengthRange, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetWavelengthRangeResponse> GetWavelengthRangeAsync(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetWavelengthRangeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetWavelengthRangeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetWavelengthRangeResponse> GetWavelengthRangeAsync(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetWavelengthRangeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetWavelengthRange, null, options, request);
      }
      public virtual global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetWavelengthResponse GetWavelength(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetWavelengthRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetWavelength(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetWavelengthResponse GetWavelength(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetWavelengthRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetWavelength, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetWavelengthResponse> GetWavelengthAsync(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetWavelengthRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetWavelengthAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetWavelengthResponse> GetWavelengthAsync(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetWavelengthRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetWavelength, null, options, request);
      }
      public virtual global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetWavelengthResponse SetWavelength(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetWavelengthRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetWavelength(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetWavelengthResponse SetWavelength(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetWavelengthRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetWavelength, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetWavelengthResponse> SetWavelengthAsync(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetWavelengthRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetWavelengthAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetWavelengthResponse> SetWavelengthAsync(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetWavelengthRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetWavelength, null, options, request);
      }
      public virtual global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetGratingOptionsResponse GetGratingOptions(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetGratingOptionsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetGratingOptions(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetGratingOptionsResponse GetGratingOptions(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetGratingOptionsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetGratingOptions, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetGratingOptionsResponse> GetGratingOptionsAsync(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetGratingOptionsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetGratingOptionsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetGratingOptionsResponse> GetGratingOptionsAsync(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetGratingOptionsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetGratingOptions, null, options, request);
      }
      public virtual global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetGratingResponse GetGrating(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetGratingRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetGrating(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetGratingResponse GetGrating(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetGratingRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetGrating, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetGratingResponse> GetGratingAsync(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetGratingRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetGratingAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetGratingResponse> GetGratingAsync(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetGratingRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetGrating, null, options, request);
      }
      public virtual global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetGratingResponse SetGrating(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetGratingRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetGrating(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetGratingResponse SetGrating(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetGratingRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetGrating, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetGratingResponse> SetGratingAsync(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetGratingRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetGratingAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetGratingResponse> SetGratingAsync(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetGratingRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetGrating, null, options, request);
      }
      public virtual global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetSlitWidthRangeResponse GetSlitWidthRange(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetSlitWidthRangeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetSlitWidthRange(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetSlitWidthRangeResponse GetSlitWidthRange(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetSlitWidthRangeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetSlitWidthRange, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetSlitWidthRangeResponse> GetSlitWidthRangeAsync(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetSlitWidthRangeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetSlitWidthRangeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetSlitWidthRangeResponse> GetSlitWidthRangeAsync(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetSlitWidthRangeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetSlitWidthRange, null, options, request);
      }
      public virtual global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetSlitWidthResponse GetSlitWidth(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetSlitWidthRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetSlitWidth(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetSlitWidthResponse GetSlitWidth(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetSlitWidthRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetSlitWidth, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetSlitWidthResponse> GetSlitWidthAsync(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetSlitWidthRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetSlitWidthAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetSlitWidthResponse> GetSlitWidthAsync(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetSlitWidthRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetSlitWidth, null, options, request);
      }
      public virtual global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetSlitWidthResponse SetSlitWidth(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetSlitWidthRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetSlitWidth(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetSlitWidthResponse SetSlitWidth(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetSlitWidthRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetSlitWidth, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetSlitWidthResponse> SetSlitWidthAsync(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetSlitWidthRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetSlitWidthAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetSlitWidthResponse> SetSlitWidthAsync(global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetSlitWidthRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetSlitWidth, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override MonochromatorClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new MonochromatorClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(MonochromatorBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Connect, serviceImpl.Connect)
          .AddMethod(__Method_Disconnect, serviceImpl.Disconnect)
          .AddMethod(__Method_GetWavelengthRange, serviceImpl.GetWavelengthRange)
          .AddMethod(__Method_GetWavelength, serviceImpl.GetWavelength)
          .AddMethod(__Method_SetWavelength, serviceImpl.SetWavelength)
          .AddMethod(__Method_GetGratingOptions, serviceImpl.GetGratingOptions)
          .AddMethod(__Method_GetGrating, serviceImpl.GetGrating)
          .AddMethod(__Method_SetGrating, serviceImpl.SetGrating)
          .AddMethod(__Method_GetSlitWidthRange, serviceImpl.GetSlitWidthRange)
          .AddMethod(__Method_GetSlitWidth, serviceImpl.GetSlitWidth)
          .AddMethod(__Method_SetSlitWidth, serviceImpl.SetSlitWidth).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, MonochromatorBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Connect, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::ConnectRequest, global::ConnectResponse>(serviceImpl.Connect));
      serviceBinder.AddMethod(__Method_Disconnect, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::DisconnectRequest, global::DisconnectResponse>(serviceImpl.Disconnect));
      serviceBinder.AddMethod(__Method_GetWavelengthRange, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetWavelengthRangeRequest, global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetWavelengthRangeResponse>(serviceImpl.GetWavelengthRange));
      serviceBinder.AddMethod(__Method_GetWavelength, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetWavelengthRequest, global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetWavelengthResponse>(serviceImpl.GetWavelength));
      serviceBinder.AddMethod(__Method_SetWavelength, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetWavelengthRequest, global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetWavelengthResponse>(serviceImpl.SetWavelength));
      serviceBinder.AddMethod(__Method_GetGratingOptions, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetGratingOptionsRequest, global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetGratingOptionsResponse>(serviceImpl.GetGratingOptions));
      serviceBinder.AddMethod(__Method_GetGrating, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetGratingRequest, global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetGratingResponse>(serviceImpl.GetGrating));
      serviceBinder.AddMethod(__Method_SetGrating, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetGratingRequest, global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetGratingResponse>(serviceImpl.SetGrating));
      serviceBinder.AddMethod(__Method_GetSlitWidthRange, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetSlitWidthRangeRequest, global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetSlitWidthRangeResponse>(serviceImpl.GetSlitWidthRange));
      serviceBinder.AddMethod(__Method_GetSlitWidth, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetSlitWidthRequest, global::Instrosetta.Interfaces.LightAnalysis.Monochromator.GetSlitWidthResponse>(serviceImpl.GetSlitWidth));
      serviceBinder.AddMethod(__Method_SetSlitWidth, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetSlitWidthRequest, global::Instrosetta.Interfaces.LightAnalysis.Monochromator.SetSlitWidthResponse>(serviceImpl.SetSlitWidth));
    }

  }
}
#endregion
