// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: instrosetta/interfaces/light/light_source.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Instrosetta.Interfaces.Light.LightSource.V1 {
  public static partial class LightSource
  {
    static readonly string __ServiceName = "instrosetta.interfaces.light.light_source.v1.LightSource";

    static readonly grpc::Marshaller<global::Instrosetta.Interfaces.Light.LightSource.V1.EchoRequest> __Marshaller_instrosetta_interfaces_light_light_source_v1_EchoRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Instrosetta.Interfaces.Light.LightSource.V1.EchoRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Instrosetta.Interfaces.Light.LightSource.V1.EchoResponse> __Marshaller_instrosetta_interfaces_light_light_source_v1_EchoResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Instrosetta.Interfaces.Light.LightSource.V1.EchoResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Instrosetta.Interfaces.Light.LightSource.V1.ConnectRequest> __Marshaller_instrosetta_interfaces_light_light_source_v1_ConnectRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Instrosetta.Interfaces.Light.LightSource.V1.ConnectRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Instrosetta.Interfaces.Light.LightSource.V1.ConnectResponse> __Marshaller_instrosetta_interfaces_light_light_source_v1_ConnectResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Instrosetta.Interfaces.Light.LightSource.V1.ConnectResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Instrosetta.Interfaces.Light.LightSource.V1.DisconnectRequest> __Marshaller_instrosetta_interfaces_light_light_source_v1_DisconnectRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Instrosetta.Interfaces.Light.LightSource.V1.DisconnectRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Instrosetta.Interfaces.Light.LightSource.V1.DisconnectResponse> __Marshaller_instrosetta_interfaces_light_light_source_v1_DisconnectResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Instrosetta.Interfaces.Light.LightSource.V1.DisconnectResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Instrosetta.Interfaces.Light.LightSource.V1.GetPowerRequest> __Marshaller_instrosetta_interfaces_light_light_source_v1_GetPowerRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Instrosetta.Interfaces.Light.LightSource.V1.GetPowerRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Instrosetta.Interfaces.Light.LightSource.V1.GetPowerResponse> __Marshaller_instrosetta_interfaces_light_light_source_v1_GetPowerResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Instrosetta.Interfaces.Light.LightSource.V1.GetPowerResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Instrosetta.Interfaces.Light.LightSource.V1.SetPowerRequest> __Marshaller_instrosetta_interfaces_light_light_source_v1_SetPowerRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Instrosetta.Interfaces.Light.LightSource.V1.SetPowerRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Instrosetta.Interfaces.Light.LightSource.V1.SetPowerResponse> __Marshaller_instrosetta_interfaces_light_light_source_v1_SetPowerResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Instrosetta.Interfaces.Light.LightSource.V1.SetPowerResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Instrosetta.Interfaces.Light.LightSource.V1.EchoRequest, global::Instrosetta.Interfaces.Light.LightSource.V1.EchoResponse> __Method_Echo = new grpc::Method<global::Instrosetta.Interfaces.Light.LightSource.V1.EchoRequest, global::Instrosetta.Interfaces.Light.LightSource.V1.EchoResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Echo",
        __Marshaller_instrosetta_interfaces_light_light_source_v1_EchoRequest,
        __Marshaller_instrosetta_interfaces_light_light_source_v1_EchoResponse);

    static readonly grpc::Method<global::Instrosetta.Interfaces.Light.LightSource.V1.ConnectRequest, global::Instrosetta.Interfaces.Light.LightSource.V1.ConnectResponse> __Method_Connect = new grpc::Method<global::Instrosetta.Interfaces.Light.LightSource.V1.ConnectRequest, global::Instrosetta.Interfaces.Light.LightSource.V1.ConnectResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Connect",
        __Marshaller_instrosetta_interfaces_light_light_source_v1_ConnectRequest,
        __Marshaller_instrosetta_interfaces_light_light_source_v1_ConnectResponse);

    static readonly grpc::Method<global::Instrosetta.Interfaces.Light.LightSource.V1.DisconnectRequest, global::Instrosetta.Interfaces.Light.LightSource.V1.DisconnectResponse> __Method_Disconnect = new grpc::Method<global::Instrosetta.Interfaces.Light.LightSource.V1.DisconnectRequest, global::Instrosetta.Interfaces.Light.LightSource.V1.DisconnectResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Disconnect",
        __Marshaller_instrosetta_interfaces_light_light_source_v1_DisconnectRequest,
        __Marshaller_instrosetta_interfaces_light_light_source_v1_DisconnectResponse);

    static readonly grpc::Method<global::Instrosetta.Interfaces.Light.LightSource.V1.GetPowerRequest, global::Instrosetta.Interfaces.Light.LightSource.V1.GetPowerResponse> __Method_GetPower = new grpc::Method<global::Instrosetta.Interfaces.Light.LightSource.V1.GetPowerRequest, global::Instrosetta.Interfaces.Light.LightSource.V1.GetPowerResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetPower",
        __Marshaller_instrosetta_interfaces_light_light_source_v1_GetPowerRequest,
        __Marshaller_instrosetta_interfaces_light_light_source_v1_GetPowerResponse);

    static readonly grpc::Method<global::Instrosetta.Interfaces.Light.LightSource.V1.SetPowerRequest, global::Instrosetta.Interfaces.Light.LightSource.V1.SetPowerResponse> __Method_SetPower = new grpc::Method<global::Instrosetta.Interfaces.Light.LightSource.V1.SetPowerRequest, global::Instrosetta.Interfaces.Light.LightSource.V1.SetPowerResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetPower",
        __Marshaller_instrosetta_interfaces_light_light_source_v1_SetPowerRequest,
        __Marshaller_instrosetta_interfaces_light_light_source_v1_SetPowerResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Instrosetta.Interfaces.Light.LightSource.V1.LightSourceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of LightSource</summary>
    public abstract partial class LightSourceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Instrosetta.Interfaces.Light.LightSource.V1.EchoResponse> Echo(global::Instrosetta.Interfaces.Light.LightSource.V1.EchoRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Instrosetta.Interfaces.Light.LightSource.V1.ConnectResponse> Connect(global::Instrosetta.Interfaces.Light.LightSource.V1.ConnectRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Instrosetta.Interfaces.Light.LightSource.V1.DisconnectResponse> Disconnect(global::Instrosetta.Interfaces.Light.LightSource.V1.DisconnectRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Instrosetta.Interfaces.Light.LightSource.V1.GetPowerResponse> GetPower(global::Instrosetta.Interfaces.Light.LightSource.V1.GetPowerRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Instrosetta.Interfaces.Light.LightSource.V1.SetPowerResponse> SetPower(global::Instrosetta.Interfaces.Light.LightSource.V1.SetPowerRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for LightSource</summary>
    public partial class LightSourceClient : grpc::ClientBase<LightSourceClient>
    {
      /// <summary>Creates a new client for LightSource</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public LightSourceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for LightSource that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public LightSourceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected LightSourceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected LightSourceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Instrosetta.Interfaces.Light.LightSource.V1.EchoResponse Echo(global::Instrosetta.Interfaces.Light.LightSource.V1.EchoRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Echo(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Instrosetta.Interfaces.Light.LightSource.V1.EchoResponse Echo(global::Instrosetta.Interfaces.Light.LightSource.V1.EchoRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Echo, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Instrosetta.Interfaces.Light.LightSource.V1.EchoResponse> EchoAsync(global::Instrosetta.Interfaces.Light.LightSource.V1.EchoRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return EchoAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Instrosetta.Interfaces.Light.LightSource.V1.EchoResponse> EchoAsync(global::Instrosetta.Interfaces.Light.LightSource.V1.EchoRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Echo, null, options, request);
      }
      public virtual global::Instrosetta.Interfaces.Light.LightSource.V1.ConnectResponse Connect(global::Instrosetta.Interfaces.Light.LightSource.V1.ConnectRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Connect(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Instrosetta.Interfaces.Light.LightSource.V1.ConnectResponse Connect(global::Instrosetta.Interfaces.Light.LightSource.V1.ConnectRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Connect, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Instrosetta.Interfaces.Light.LightSource.V1.ConnectResponse> ConnectAsync(global::Instrosetta.Interfaces.Light.LightSource.V1.ConnectRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ConnectAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Instrosetta.Interfaces.Light.LightSource.V1.ConnectResponse> ConnectAsync(global::Instrosetta.Interfaces.Light.LightSource.V1.ConnectRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Connect, null, options, request);
      }
      public virtual global::Instrosetta.Interfaces.Light.LightSource.V1.DisconnectResponse Disconnect(global::Instrosetta.Interfaces.Light.LightSource.V1.DisconnectRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Disconnect(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Instrosetta.Interfaces.Light.LightSource.V1.DisconnectResponse Disconnect(global::Instrosetta.Interfaces.Light.LightSource.V1.DisconnectRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Disconnect, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Instrosetta.Interfaces.Light.LightSource.V1.DisconnectResponse> DisconnectAsync(global::Instrosetta.Interfaces.Light.LightSource.V1.DisconnectRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DisconnectAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Instrosetta.Interfaces.Light.LightSource.V1.DisconnectResponse> DisconnectAsync(global::Instrosetta.Interfaces.Light.LightSource.V1.DisconnectRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Disconnect, null, options, request);
      }
      public virtual global::Instrosetta.Interfaces.Light.LightSource.V1.GetPowerResponse GetPower(global::Instrosetta.Interfaces.Light.LightSource.V1.GetPowerRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetPower(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Instrosetta.Interfaces.Light.LightSource.V1.GetPowerResponse GetPower(global::Instrosetta.Interfaces.Light.LightSource.V1.GetPowerRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetPower, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Instrosetta.Interfaces.Light.LightSource.V1.GetPowerResponse> GetPowerAsync(global::Instrosetta.Interfaces.Light.LightSource.V1.GetPowerRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetPowerAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Instrosetta.Interfaces.Light.LightSource.V1.GetPowerResponse> GetPowerAsync(global::Instrosetta.Interfaces.Light.LightSource.V1.GetPowerRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetPower, null, options, request);
      }
      public virtual global::Instrosetta.Interfaces.Light.LightSource.V1.SetPowerResponse SetPower(global::Instrosetta.Interfaces.Light.LightSource.V1.SetPowerRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPower(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Instrosetta.Interfaces.Light.LightSource.V1.SetPowerResponse SetPower(global::Instrosetta.Interfaces.Light.LightSource.V1.SetPowerRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetPower, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Instrosetta.Interfaces.Light.LightSource.V1.SetPowerResponse> SetPowerAsync(global::Instrosetta.Interfaces.Light.LightSource.V1.SetPowerRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPowerAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Instrosetta.Interfaces.Light.LightSource.V1.SetPowerResponse> SetPowerAsync(global::Instrosetta.Interfaces.Light.LightSource.V1.SetPowerRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetPower, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override LightSourceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new LightSourceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(LightSourceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Echo, serviceImpl.Echo)
          .AddMethod(__Method_Connect, serviceImpl.Connect)
          .AddMethod(__Method_Disconnect, serviceImpl.Disconnect)
          .AddMethod(__Method_GetPower, serviceImpl.GetPower)
          .AddMethod(__Method_SetPower, serviceImpl.SetPower).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, LightSourceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Echo, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Instrosetta.Interfaces.Light.LightSource.V1.EchoRequest, global::Instrosetta.Interfaces.Light.LightSource.V1.EchoResponse>(serviceImpl.Echo));
      serviceBinder.AddMethod(__Method_Connect, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Instrosetta.Interfaces.Light.LightSource.V1.ConnectRequest, global::Instrosetta.Interfaces.Light.LightSource.V1.ConnectResponse>(serviceImpl.Connect));
      serviceBinder.AddMethod(__Method_Disconnect, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Instrosetta.Interfaces.Light.LightSource.V1.DisconnectRequest, global::Instrosetta.Interfaces.Light.LightSource.V1.DisconnectResponse>(serviceImpl.Disconnect));
      serviceBinder.AddMethod(__Method_GetPower, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Instrosetta.Interfaces.Light.LightSource.V1.GetPowerRequest, global::Instrosetta.Interfaces.Light.LightSource.V1.GetPowerResponse>(serviceImpl.GetPower));
      serviceBinder.AddMethod(__Method_SetPower, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Instrosetta.Interfaces.Light.LightSource.V1.SetPowerRequest, global::Instrosetta.Interfaces.Light.LightSource.V1.SetPowerResponse>(serviceImpl.SetPower));
    }

  }
}
#endregion
